PREFIX : <http://data.treehouse.example/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# Insert all Enterprise customers as members of the Enterprise CRM portfolio.

CONSTRUCT {
    :EnterpriseCRM rdf:type :Portfolio .
    ?customer :memberOf :EnterpriseCRM .
}
WHERE {
  ?customer rdf:type :Customer ;
    :segment ?segment .

    FILTER(STR(?segment) = "Enterprise")
}